-- 코드를 작성해주세요
SELECT
    T.ID,
    CASE
        WHEN T.TILE = 1 THEN 'CRITICAL'
        WHEN T.TILE = 2 THEN 'HIGH'
        WHEN T.TILE = 3 THEN 'MEDIUM'
        ELSE 'LOW'
    END AS COLONY_NAME
FROM 
    (
    SELECT ID, NTILE(4) OVER (ORDER BY SIZE_OF_COLONY DESC) AS TILE FROM ECOLI_DATA
    ) AS T
ORDER BY
    T.ID ASC