-- 코드를 작성해주세요
SELECT
    c.ID, c.GENOTYPE, p.GENOTYPE AS PARENT_GENOTYPE
FROM
    ECOLI_DATA AS p
LEFT JOIN
    ECOLI_DATA AS c ON p.ID = c.PARENT_ID
WHERE
    c.GENOTYPE & p.GENOTYPE = P.GENOTYPE
ORDER BY
    c.ID ASC